name: apn_state
description: An Appnormal flutter package, providing state management based on Flutter Provider and Event Bus for state-to-state communication.
version: 1.2.1
homepage: https://github.com/appnormal/apn_state

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  get_it: ^4.0.2
  provider: ^4.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

