name: apn_state
description: An Appnormal flutter package, providing state management based on Flutter Provider and Event Bus for state-to-state communication.
version: 2.0.0
homepage: https://github.com/appnormal/apn_state

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^5.0.0

dev_dependencies:
  lint: ^1.5.3
  flutter_test:
    sdk: flutter

flutter:

